version: "3.8"

services:
  db:
    container_name: ips_db
    image: postgres:14-alpine
    restart: always
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DATABASE_DB=ips_db
    ports:
      - 5432:5432
    networks:
     - ips-network
  
  pgadmin:
    container_name: django_pgadmin
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5051:80
    networks:
      - ips-network

  app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: ips_management_web
    hostname: app
    stdin_open: true
    expose:
      - '8000'
    volumes:
      - .env.docker:/app/.env
    command: bash -c "python manage.py migrate && gunicorn setup.wsgi:application -b 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - ips-network

  nginx:
    container_name: ips_nginx
    image: nginx
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/config/nginx/:/etc/nginx/conf.d/
      - ./Backend/staticfiles/:/home/python/app/staticfiles
      - ./Backend/media/:/home/python/app/media
    depends_on:
      - app
    networks:
      - ips-network

volumes:
  pgdata:
  pgadmin:

networks:
  ips-network:
