# Generated by Django 4.1.7 on 2023-04-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('cpf_number', models.CharField(blank=True, max_length=11, unique=True)),
                ('rg_number', models.CharField(max_length=9, unique=True)),
                ('issuing_entity', models.CharField(blank=True, max_length=30)),
                ('naturalness', models.CharField(blank=True, max_length=110)),
                ('address', models.CharField(max_length=220)),
                ('cep_number', models.CharField(max_length=9)),
                ('phone_number', models.CharField(max_length=14)),
                ('email_address', models.EmailField(max_length=80)),
            ],
        ),
    ]
